# Generated by Django 4.2.4 on 2023-09-12 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="Дата підписки")),
                (
                    "cat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cats.cat", verbose_name="Кіт"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Потенційний хазяїн",
                    ),
                ),
            ],
        ),
    ]
