# Generated by Django 4.2.4 on 2023-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=15, verbose_name="Кличка")),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="Вік")),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Хлопчик"), ("female", "Дівчинка")], max_length=10, verbose_name="Стать"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")),
                ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата оновлення")),
                ("booking_status", models.BooleanField(default=False, verbose_name="Стан заброньованості")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Фото")),
            ],
        ),
    ]
