# Generated by Django 4.2.4 on 2023-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_city_user_phone_number_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name="Номер телефону"),
        ),
    ]
